---
- name: Set namespace variables
  set_fact:
    user_namespace_name: "{{ meta.name }}"

- name: Delete Namespace
  k8s:
    state: absent
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.api_exists | default(True)
  loop:
    - name: namespace.yaml.j2

- name: Delete Secret
  k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: default
    name: "kubeconfig-{{ user_namespace_name }}"
