---
- name: Set namespace variables
  set_fact:
    namespace_name: "{{ meta.name }}"
    serviceaccount_name: "{{ meta.name }}-admin"

- name: Create Namespace
  k8s:
    state: present
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.api_exists | default(True)
  loop:
    - name: namespace.yaml.j2
    - name: service-account.yaml.j2
    - name: rbac-rolebinding.yaml.j2

- name: Read ServiceAccounts
  k8s:
    state: present
    api_version: v1
    kind: ServiceAccount
    namespace: "{{ namespace_name }}"
    name: "{{ serviceaccount_name }}"
  register: sa_result

- name: Read Secret
  k8s:
    state: present
    api_version: v1
    kind: Secret
    namespace: "{{ namespace_name }}"
    name: "{{ sa_result.result.secrets[0].name }}"
  register: service_result

- name: Create Secret
  k8s:
    state: present
    api_version: v1
    kind: Secret
    namespace: default
    name: "namespace-{{ namespace_name }}"
    definition:
      data: "{{ service_result.result.data }}"
